name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        npm ls @capacitor/cli || echo "Capacitor CLI not found"
        npm ls vite || echo "Vite not found in dependencies"
      
    - name: Build mobile app
      run: |
        chmod +x node_modules/.bin/vite || echo "Vite binary not found"
        npm run build:mobile
        ls -la dist/ || echo "Dist folder not created"
      
    - name: Sync Capacitor
      run: |
        chmod +x node_modules/.bin/cap || echo "Cap binary not found"
        npx cap info || echo "Capacitor info check"
        npx cap sync android
        ls -la android/ || echo "Android folder check"
      
    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: money-manager-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Get APK info
      run: |
        APK_PATH="android/app/build/outputs/apk/debug/app-debug.apk"
        if [ -f "$APK_PATH" ]; then
          APK_SIZE=$(du -h "$APK_PATH" | cut -f1)
          echo "✅ ClarityOS APK built successfully!"
          echo "📱 APK Size: $APK_SIZE"
          echo "📁 APK Path: $APK_PATH"
          echo "⚡ ClarityOS is ready for installation!"
        else
          echo "❌ APK build failed!"
          exit 1
        fi